Article.delete_all
Comment.delete_all
a1 = Article.create(title: "An Important Article", author: "Cooper Mayne", body: "something important written here something important written here something important written here something important written here something important written here something important written here something important written here something important written here something important written heresomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here s")
a2 = Article.create(title: "A Stupid Article", author: "Sam Mayne", body: "something important written here something important written here something important written here something important written here something important written here something important written here something important written here something important written here something important written heresomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here s")
a3 = Article.create(title: "A Smarth Article", author: "Thom Mayne", body: "something important written here something important written here something important written here something important written here something important written here something important written here something important written here something important written here something important written heresomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here ssomething important written here s")

c1 = Comment.create(body: "i love it")
c2 = Comment.create(body: "i hate it")
c3 = Comment.create(body: "i dont care about it")

c4 = Comment.create(body: "jimmy wrote this!")
c5 = Comment.create(body: "johnny wrote this!")

a2.comments << c4 << c5
a1.comments << c1 << c2 << c3

