development:
  adapter: postgresql
  encoding: unicode
  database: Blog_development
  pool: 5
  username: postgres
  password: home3232
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: Blog_test
  pool: 5
  username: postgres
  password: home3232
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: Blog_production
  pool: 5
  username: postgres
  password: home3232
  host: localhost
