words = ["dog",
          "cat",
          "words",
          "wordsmith",
          "author",
          "novel",
          "story",
          "game",
          "beachfront",
          "regulation",
          "bankruptcy",
          "education",
          "democrat",
          "republican",
          "healthcare",
          "nurse",
          "drugs",
          "copyright"];
