development:
  consumer_key: JSPEHTHsmt8SPOo09PljcQ
  consumer_secret: roMNGuN4ATZAkXxNLNb5WrwQPhiL8j9oRP11058jNvE
  oauth_token: 1464668084-ZSyGijIqzDyjq9ORjyjsNKChdxzZ6qSvLmviHaW
  oauth_token_secret: 8GUUXS4yhARX1KLWoUH8H2Bq3YIAKXlttXcLS2zM
